# Generated by Django 5.0.3 on 2024-03-11 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posthistory",
            old_name="updated_by",
            new_name="user",
        ),
    ]
