# Generated by Django 5.0.3 on 2024-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history_app", "0002_rename_updated_by_posthistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="posthistory",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
