# Generated by Django 5.0.3 on 2024-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0003_blog_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
